import re 

def process_string(raw_str):
    return raw_str.replace(r"\text{qxx}","Q_{xx}").replace(r"\text{qxy}","Q_{xy}")\
    .replace(r"\text{qxz}", "Q_{xz}")\
    .replace(r"\text{qyz}","Q_{yz}").replace(r"\text{qzz}","Q_{zz}")\
    .replace(r"\text{px}","k_x").replace(r"\text{py}","k_y").replace(r"\text{pz}","k_z")\
    .replace(r"\text{vy}","v_y").replace(r"\text{vx}","v_x").replace(r"\text{$\gamma $d}","\dot\gamma")

veqn1 = r"\frac{a \tau  \left(\text{qyz}''+i \left(\text{px} \text{qxz}'+\text{pz} \text{qxx}'+2 \text{pz} \text{qzz}'\right)\right)+a \text{pz} \tau  (\text{px} \text{qxy}+\text{pz} \text{qyz})-i \eta  \text{pz} \text{vy} \left(\text{px}^2+\text{pz}^2\right)+i \eta  \text{pz} \text{vy}''}{\eta  \tau }"
veqn2 = r"\frac{a \tau  \left(\text{px}^2 \text{qxz}+\text{px} \text{pz} (\text{qzz}-\text{qxx})-\text{pz}^2 \text{qxz}\right)-i \left(a \text{px} \tau  W \text{Qyz}'(W Y)-a \text{pz} \tau  \text{qxy}'+\eta  \text{pz} \text{vx}''\right)+i \eta  \text{pz} \text{vx} \left(\text{px}^2+\text{pz}^2\right)}{\eta  \tau }"
veqn3 = r"W^2 \text{Vx}^{(3)}(W Y)+\frac{i \left(i a \text{px} \tau  (\text{px} \text{qxy}+\text{pz} \text{qyz})-2 a \text{px} \tau  \text{qxx}'-a \text{px} \tau  \text{qzz}'-a \text{pz} \tau  \text{qxz}'+i a \tau  \text{qxy}''+i \eta  \left(\text{px}^2+\text{pz}^2\right) \text{vx}'+\eta  \text{px} \text{vy} \left(\text{px}^2+\text{pz}^2\right)-\eta  \text{px} \text{vy}''\right)}{\eta  \tau }"

qxxeqn = r"\frac{\text{ell}^2 \left(\text{qxx} \left(\text{px}^2+\text{pz}^2\right)-\text{qxx}''\right)}{W^2}-4 i \lambda  \text{px} \text{qxx} \text{vx}+i \text{px} \text{qxx} (\text{vx}+\text{$\gamma $d} \tau  Y)-\lambda  \text{qxy} \left(\text{$\gamma $d} \tau +i \text{px} \text{vy}+\text{vx}'\right)-\text{qxy} \left(\text{$\gamma $d} \tau -i \text{px} \text{vy}+\text{vx}'\right)+\frac{\lambda  \left(\text{$\gamma $d}^2 \tau ^2 (\lambda -2 i ((\lambda -2) \lambda -1) \text{px} \text{vx}+1)+8 i \text{px} \text{vx}+2 i \text{$\gamma $d} (\lambda -1) \text{px} \tau  \text{vy}+2 \text{$\gamma $d} \tau  \left((\lambda +1) \text{vx}'-\text{$\gamma $d} (\lambda -1) \lambda  \tau  \text{vy}'\right)\right)}{\text{$\gamma $d}^2 \left(3 \lambda ^2-1\right) \tau ^2-4}-i \lambda  \text{pz} \text{qxz} \text{vx}-i \text{pz} \text{qxz} \text{vx}+2 i \lambda  \text{pz} \text{qyz} \text{vy}+\text{vy} \text{qxx}'-2 \lambda  (\text{qxx}+\text{qzz}) \text{vy}'+\text{qxx} \sigma  \tau +\text{qxx}"
qxyeqn = r"\frac{1}{2} \left(\frac{2 \text{ell}^2 \left(\text{qxy} \left(\text{px}^2+\text{pz}^2\right)-\text{qxy}''\right)}{W^2}+3 \lambda  \left(\text{qzz} \text{vx}'-i \left(2 \text{px} \text{qxy} \text{vx}-\text{px} \text{qzz} \text{vy}+\text{pz} \text{qxz} \text{vy}+\text{pz} \text{qyz} \text{vx}-2 i \text{qxy} \text{vy}'+i \text{$\gamma $d} \text{qzz} \tau \right)\right)+(\text{qxx}+\text{qzz}) \left(\text{$\gamma $d} \tau -i \text{px} \text{vy}+\text{vx}'\right)+\text{qxx} \left(\text{$\gamma $d} \tau -i \text{px} \text{vy}+\text{vx}'\right)+2 i \text{px} \text{qxy} (\text{vx}+\text{$\gamma $d} \tau  Y)+\frac{4 \lambda  \left(\text{$\gamma $d} \tau +i \text{px} \left(3 \text{$\gamma $d} \lambda  \tau  \text{vx}+\text{$\gamma $d}^2 \tau ^2 \text{vy}+2 \text{vy}\right)+2 \text{vx}'+3 \text{$\gamma $d} \lambda  \tau  \text{vy}'\right)}{\text{$\gamma $d}^2 \left(3 \lambda ^2-1\right) \tau ^2-4}-i \text{pz} \text{qxz} \text{vy}-i \text{pz} \text{qyz} \text{vx}+2 \text{vy} \text{qxy}'+2 \text{qxy} \sigma  \tau +2 \text{qxy}\right)"
qxzeqn = r"\frac{1}{2} \left(\frac{2 \text{ell}^2 \text{qxz} \left(\text{px}^2+\text{pz}^2\right)}{W^2}-\frac{2 \text{ell}^2 \text{qxz}''}{W^2}+2 i (1-3 \lambda ) \text{px} \text{qxz} \text{vx}+2 \text{qxz} \tau  (\sigma +i \text{$\gamma $d} \text{px} Y)+i (1-3 \lambda ) \text{px} \text{qyz} \text{vy}-3 i \lambda  \text{pz} \text{qxx} \text{vx}+i \text{pz} \text{qxx} \text{vx}-3 i \lambda  \text{pz} \text{qxy} \text{vy}+i \text{pz} \text{qxy} \text{vy}-3 i \lambda  \text{pz} \text{qzz} \text{vx}-i \text{pz} \text{qzz} \text{vx}-\frac{i \lambda  \text{pz} \left(\text{vx} \left(\text{$\gamma $d}^2 \left(9 \lambda ^2-1\right) \tau ^2-8\right)+2 \text{$\gamma $d} (1-3 \lambda ) \tau  \text{vy}\right)}{\text{$\gamma $d}^2 \left(3 \lambda ^2-1\right) \tau ^2-4}+2 \text{vy} \text{qxz}'+2 \text{qxz}-(3 \lambda +1) \text{qyz} \left(\text{$\gamma $d} \tau +\text{vx}'\right)\right)"
qyzeqn = r"\frac{1}{2} \left(2 \text{qyz} \left(\frac{\text{ell}^2 \left(\text{px}^2+\text{pz}^2\right)}{W^2}+i \text{px} (\text{vx}+\text{$\gamma $d} \tau  Y)+\sigma  \tau -3 \lambda  \text{vy}'+1\right)-\frac{2 \text{ell}^2 \text{qyz}''}{W^2}+\text{qxz} \left(\text{$\gamma $d} (1-3 \lambda ) \tau -i \text{px} (3 \lambda  \text{vy}+\text{vy})+(1-3 \lambda ) \text{vx}'\right)+3 i \lambda  \text{pz} \text{qxx} \text{vy}-i \text{pz} \text{qxx} \text{vy}-3 i \lambda  \text{pz} \text{qxy} \text{vx}+i \text{pz} \text{qxy} \text{vx}-2 i \text{pz} \text{qzz} \text{vy}+\frac{i \lambda  \text{pz} \left(2 \text{$\gamma $d} (3 \lambda -1) \tau  \text{vx}+\text{vy} \left(8-3 \text{$\gamma $d}^2 (\lambda +1) (3 \lambda -1) \tau ^2\right)\right)}{\text{$\gamma $d}^2 \left(3 \lambda ^2-1\right) \tau ^2-4}+2 \text{vy} W \text{Qyz}'(W Y)\right)"
qzzeqn = r"\frac{\text{ell}^2 \left(\text{qzz} \left(\text{px}^2+\text{pz}^2\right)-\text{qzz}''\right)}{W^2}+2 \lambda  \left(i (\text{px} \text{qxx} \text{vx}+\text{px} \text{qxy} \text{vy}+\text{pz} \text{qxz} \text{vx}+\text{pz} \text{qyz} \text{vy})-(\text{qxx}+\text{qzz}) \text{vy}'+\text{$\gamma $d} \text{qxy} \tau +\text{qxy} \text{vx}'\right)+i \text{px} \text{qzz} (\text{vx}+\text{$\gamma $d} \tau  Y)+\frac{2 \text{$\gamma $d} \lambda ^2 \tau  \left(-\text{$\gamma $d} \tau -i \text{px} (\text{$\gamma $d} (\lambda +1) \tau  \text{vx}+2 \text{vy})-2 \text{vx}'-\text{$\gamma $d} (\lambda -1) \tau  \text{vy}'\right)}{\text{$\gamma $d}^2 \left(3 \lambda ^2-1\right) \tau ^2-4}-3 i \lambda  \text{pz} (\text{qxz} \text{vx}+\text{qyz} \text{vy})+i \text{pz} \text{qxz} \text{vx}+i \text{pz} \text{qyz} \text{vy}+\text{vy} \text{qzz}'+\text{qzz} \sigma  \tau +\text{qzz}"

eqns = [veqn1, veqn2, veqn3, qxxeqn, qxyeqn, qxzeqn, qyzeqn, qzzeqn]

with open("equations.txt", "w") as text_file:
    for eqn in eqns:
        text_file.write(process_string(eqn))
        text_file.write("\n\n")